### ISSUE TITLE
Fix Avatar in About section

### ISSUE THREAD

**Issue by hrsh22** [Git-For-Geeks/Portfolio-Website#1]
The avatar must be in circular shape. Remove the visible background from the image.

**Comment by Mrugal4** [comment]
Hi @hrsh22 ,
I would like to work on this issue , also I would like to Contact Me section .

**Comment by hrsh22** [comment]
Hey @Mrugal4 you can work on this issue for now and create another issue for contact section after Issue #5 is closed.
