### ISSUE TITLE
Improve footer structure

### ISSUE THREAD

**Issue by hrsh22** [Git-For-Geeks/Portfolio-Website#4]
Improve the structure of the footer and adjust its height according to the text.

**Comment by Shrutijn20** [comment]
Please assign this task to me.

**Comment by Mrugal4** [comment]
Hi @hrsh22 
What kind of improvement is needed in footer section ?

**Comment by hrsh22** [comment]
Hi @Mrugal4 
We can decrease the height of the footer a bit and also add a 'Go to Top' button. You can suggest if you think anymore improvement is needed.

**Comment by Mrugal4** [comment]
Hi @hrsh22 
I have done the respective changes and tried fixing these issue .
Kindly review my PR .
